//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Web.Models
{
    using System;
    
    public enum CompanyStatus : int
    {
        ACTIVE = 1,
        DISABLED = 2,
        EXPECTATION = 3
    }
}
