//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.Exams = new HashSet<Exam>();
            this.UserCourses = new HashSet<UserCours>();
            this.Modules = new HashSet<Module>();
        }
    
        public int CourseId { get; set; }
        public string Name { get; set; }
        public int RequiredPassScore { get; set; }
        public bool RandomizeQuestionOrder { get; set; }
    
        public virtual ICollection<Exam> Exams { get; set; }
        public virtual ICollection<UserCours> UserCourses { get; set; }
        public virtual ICollection<Module> Modules { get; set; }
    }
}
