//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamQuestion
    {
        public int ExamQuestionId { get; set; }
        public int ExamId { get; set; }
        public int ModuleQuestionId { get; set; }
        public bool Answered { get; set; }
        public Nullable<bool> WasCorrect { get; set; }
        public int SortOrder { get; set; }
    
        public virtual Exam Exam { get; set; }
        public virtual ModuleQuestion ModuleQuestion { get; set; }
    }
}
