//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleQuestion
    {
        public ModuleQuestion()
        {
            this.ExamQuestions = new HashSet<ExamQuestion>();
        }
    
        public int QuestionId { get; set; }
        public int ModuleId { get; set; }
        public string ImageUrl1 { get; set; }
        public string ImageUrl2 { get; set; }
        public bool IsImage1Correct { get; set; }
        public bool IsImage2Correct { get; set; }
    
        public virtual ICollection<ExamQuestion> ExamQuestions { get; set; }
        public virtual Module Module { get; set; }
    }
}
