//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleQuestionCompany
    {
        public int ModuleCompanyId { get; set; }
        public int ModuleId { get; set; }
        public int CompanyId { get; set; }
        public int NumCorrect { get; set; }
        public int NumWrong { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual Company Company { get; set; }
    }
}
