//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.UserCourses = new HashSet<UserCours>();
            this.UserModulesWatcheds = new HashSet<UserModulesWatched>();
        }
    
        public int UserProfileId { get; set; }
        public string AspNetUserId { get; set; }
        public int CompanyId { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public int DepartmentId { get; set; }
        public Nullable<int> isCreated { get; set; }
        public string UserKey { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Department Department { get; set; }
        public virtual ICollection<UserCours> UserCourses { get; set; }
        public virtual ICollection<UserModulesWatched> UserModulesWatcheds { get; set; }
        public virtual Company Company { get; set; }
    }
}
