//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCours
    {
        public int UserCourseId { get; set; }
        public int UserProfileId { get; set; }
        public int CourseId { get; set; }
        public Nullable<int> CurrentModuleId { get; set; }
        public Nullable<int> LastModuleId { get; set; }
        public bool Completed { get; set; }
        public int MaxUserScore { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<bool> HasPassed { get; set; }
        public Nullable<int> NumTries { get; set; }
        public Nullable<bool> AllowedExam { get; set; }
    
        public virtual Course Cours { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
